### ISSUE TITLE
Question: Set time duration

### ISSUE THREAD

**Issue by PicosePablo** [mobius3/tweeny#7]
Hi, first of all, nice work.
Is there any function (or maybe u can add it) to set a tween time duration?
i.e: `tween.from(0).to(100).time(10)`
if there is, I cannot found it, the only similar "thing"  is the duration, but I dont really understand this function name, because it is logic that this define the number (maybe) frames (OR THE STEPS) that the tween needs to end, in my opinion OF COURSE :D 
EDIT:
I see the comment in the `during` function, but I cannot understand how, for example, make a 2 seconds of tween with a simple float
`tweeny::from(0.f).to(700.f).during(600000000000)`
during parameter ignore the value, if I set another biggest value, it does not care xD
can you explain me that please?

**Comment by mobius3** [comment]
Hi!

I'm not sure why `.during()` is not working for you. How/when are you calling `step` on your tweens?

Tweeny itself has no time control, that is left for the user to do. In other words, you are right, `.during()` really does specifies the number of steps required to complete the tween. You can use that to make your tween last as long as you want. For instance, to make a two second tween, I'd use something like this:

```
auto t = tweeny::from(0).to(100).during(2000) // I'm using 2000 as miliseconds
```

then after I get the delta-time of my frames, I'd step the tween by that amount:

```
while (!finished) {
  int dt = game.getDeltaTime() // or calculate this manually between frames
  t.step(dt);
}
```

after 2000 miliseconds the tween would be complete. But thats only because the amount I'm using to step is on the same scale as the number specified in `during`.

**Comment by mobius3** [comment]
Hi @PicosePablo, any update on this?

**Comment by mobius3** [comment]
I'm closing this issue. If there's any update, feel free to reopen it.
